export const db = "main-db"
export const questionCollection = "questions"
export const answerCollection = "answers"
export const commentsCollection = "comments"
export const voteCollection = "votes"
export const questionAttachmentBucket = "question-attachments"
